### ISSUE TITLE
GQLAlchemy can't be installed with Python 3.10 on Windows

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/gqlalchemy#179]
Currently, GQLAlchemy can't be installed with Python 3.10 on Windows, since its dependencies still do not support Python 3.10. For example, GQLAlchemy has NetworkX as a dependency and it has numpy as its dependency. There is no version of numpy that works with Python 10 on Windows. Once all dependencies are supported for Python 3.10, we can update the appropriate packages and add Python 3.10 support for Windows.

**Comment by jngarber-st** [comment]
What is the path forward here? I wouldn't mind using an older version of python to use this library, but curious if there is an ETA on making it compatible with 3.11. Python.org no longer provides installers for 3.9. NetworkX and numpy both have versions that support python 3.11. I was unable to install pymgclient on both my Windows and Mac dev computers. I'm assuming because of the lack of 3.11 support?

**Comment by katarinasupe** [comment]
Hi @jngarber-st, we will work on the release at the end of the next week and try to include this in the release. Hopefully, dependencies that were not working properly for Python 3.10 work now. I will keep you updated here.
