### ISSUE TITLE
[BUG] can not install gqlalchemy in python 3.11.1

### ISSUE THREAD

**Issue by seabnavin19** [memgraph/gqlalchemy#236]
I have create a virtual environment for my project but when I try to install gqlalchemy I got this error
``` error
Collecting pymgclient==1.2.0
  Using cached pymgclient-1.2.0.tar.gz (122 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\seab.navin\AppData\Local\Temp\3\pip-install-_egmworm\pymgclient_3144766b603c48ed8b97ca8896114966\setup.py", line 21, in <module>
          from distutils.core import DistutilsExecError, DistutilsPlatformError
      ImportError: cannot import name 'DistutilsExecError' from 'distutils.core' (D:\Development\memmmmmmgraph\Memgraph_Fruad_Detection\venv\Lib\site-packages\setuptools\_distutils\core.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by katarinasupe** [comment]
Hi @seabnavin19, as noted in [install prerequisites](https://memgraph.com/docs/gqlalchemy/installation#prerequisites), GQLAlchemy currently can't be installed with Python 3.11. Please check the docs for the correct prerequisites to use GQLalchemy. Since you created a virtual environment, it's best you use Python 3.9 for Windows or Python 3.10 for other OS. I will leave this issue open as and link it to development as soon as we have this resolved. 

Is this a blocker for you? What are you working on? Can you share more about the use case?

**Comment by seabnavin19** [comment]
Thanks for your help, I change my python version to 3.9 and it work,
but when I try to follow the documentation of gqlacehmy in memgraph website here: https://memgraph.com/docs/gqlalchemy/how-to-guides/ogm

and I always getting this error

``` error
  File "C:\Users\seab.navin\AppData\Roaming\Python\Python39\site-packages\gqlalchemy\exceptions.py", line 235, in _handler
    raise GQLAlchemyWaitForConnectionError(ex)
TypeError: __init__() takes 1 positional argument but 2 were given
````

**Comment by seabnavin19** [comment]
Thanks for your help, After I change python to version 3.9 it works fine
